In [1]:
print ("ansar ali")

ansar ali


In [2]:
print("hello world")


hello world


In [5]:
import numpy as np
# 1) creating the array
# 2) performing operations on array
# np.__version__
# It is used to check the version of array
# To create array
#syntax
#    var  =np.array(collection)

L=[1,2,3,4,5,6]
type(L)


list

In [6]:
import numpy as np
L=[1,2,3,4,5,6]
a= np.array(L)
type(a)

numpy.ndarray

In [ ]:
arr=np.array([1,4,5,6])
#type(arr)
arr2=np.array((1,4,5,6))
#type(arr2)

I=[True,55,3.5,'hello',2-3j]
type(I[0])

bool

In [ ]:
A=np.array([True,3.2,False,3-2j,'hey',True,2,False,True,{1,2,3}])

ARR1=np.array([10,20,22,33])
ARR2=np.array([100,201,222,79])
ARR1-ARR2
ARR1*ARR2
#NUMBER OF ELEMENTS IN BOTH THE ARRAYS MUST BE EQUAL


array([1000, 4020, 4884, 2607])

In [45]:
A=np.array([[[[10,20,22,33],
             [3,6,3,11]],
             [[88,22,11,42],
             [76,95,35,72]]]])
A.ndim

#var.ndim 
#it will return the number of dimensions of the array


4

In [58]:
B= np.array([[[1,5,68,85],
             [56,31,42,41],
             [1,2,3,4]]])
B.ndim
#np.arrange(start,stop,step):
#It will create an array of integers between specififed limits.
z=np.arange(1,27)
z
#var.reshape():
#It will convert 1d array into another
#var.reshape(rows,columns)a
b=np.arange(1,17)
b.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
import numpy as np
E=np.arange(10,130)
E.reshape(6,2,10)

array([[[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]],

       [[ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]],

       [[110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129]]])

In [10]:
a=np.arange(1,31)
a.reshape(3,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [73]:
c=np.arange(1,31)
c.reshape(3,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [12]:
A=np.arange(11,55)
A

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [5]:
import numpy as np
#var.shape
#It is used  to check the number of elements present in the array
a=np.arange(1,25)
b=a.reshape((6,4))
c=a.reshape((2,3,4))
a.shape
b.shape
c.shape

#np.linspace(start,stop,n)
#n means n number values 
#linspace give n number of values which have equal space in between
#It will create an array with n number of equally distributed values between given range.
d=np.linspace(1,10,3)
d
e=np.linspace(1,5,20)
e



#np.zeros() --> It is used to create a dummy array consist of zero
# 1) np.zeros(n)
# 2) np.zeros((rows,columns))
# 3) np.zeros((rows,columns,depth))


array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [32]:
import numpy as np
f=np.zeros(7)
f
#it will create 1d array consist of zero
z=np.zeros((3,5))
z
#it will create 2d array consist of zero
x=np.zeros((2,4,3))
x
#it will create 3d array consist of zero


# np.ones() --> it is used create a dummy array consist of one
# 1) np.ones(n_of_values) -->it will create 1d array consist of ones
# 2) np.ones((rows,columns))-->it will create 2d array consist of ones
# 3) np.ones((rows,columns,depth))-->it will create 3d array consist of ones

s=np.ones(6)
s
s=np.ones((4,3))
s
s=np.ones((3,3,2))
s

#np.identity(n)
#it will create a identity matrix
f=np.identity(4)
f

#np.eye(n)

e=np.eye(5)
e
#it will create identity matrix and remaining elements will be filled with zeros.
e=np.eye(4,6)
e

#np.random.randit(SV,EV,N_of values)
e=np.random.randint(1,20,5)
e
#np.random.rand(n_of_values)

#it will generate number random values between 0 to 1
sf=np.random.rand(4)
sf
ss=np.random.rand(2,4,3)
ss

array([[[0.59559301, 0.74856832, 0.92147717],
        [0.23059497, 0.26615657, 0.04403153],
        [0.88858726, 0.16098048, 0.58552377],
        [0.68193115, 0.57557552, 0.96909242]],

       [[0.92091885, 0.70161243, 0.77483235],
        [0.43186916, 0.43640606, 0.72015606],
        [0.21610081, 0.53311538, 0.88765146],
        [0.68050389, 0.57609586, 0.06882605]]])

In [35]:
#np.random.randn(n_of_values)
#it will return the 1d array consist  of n number of values between -infinity to +infinity ,but mostly it will return between -3 to +3.
a=np.random.randn(6)
a

b=np.random.randn(3,4)
b

c=np.random.randn(3,4,2)
c

array([[[-0.76120686, -1.12172774],
        [ 1.11269815,  1.22414761],
        [-1.60145621, -0.50418391],
        [-1.3147797 , -0.26412577]],

       [[-0.02684093, -0.46032869],
        [ 1.59985992,  2.16289788],
        [-0.39951167, -0.61060693],
        [-1.34221278, -0.12900634]],

       [[ 0.63072811, -1.13088358],
        [ 0.09814759,  0.11973679],
        [-0.59751659,  2.31331611],
        [ 0.36229697,  0.06148198]]])

In [3]:
#np.full((n),value)
# it  will create an array filled with specified value
a=np.full((5),5)
a


b=np.full((5),'hello')
b


c=np.full((3,2),'HELLOWORLD')
c


d=np.full((2,4,3),'fuu')
d

array([[['fuu', 'fuu', 'fuu'],
        ['fuu', 'fuu', 'fuu'],
        ['fuu', 'fuu', 'fuu'],
        ['fuu', 'fuu', 'fuu']],

       [['fuu', 'fuu', 'fuu'],
        ['fuu', 'fuu', 'fuu'],
        ['fuu', 'fuu', 'fuu'],
        ['fuu', 'fuu', 'fuu']]], dtype='<U3')

In [2]:
import numpy as np
a=np.arange(1,25)
b=a.reshape((4,6))
c=a.reshape((3,2,4))
c
a[3:17:2]
a[0]

b[3:4]
b[2][3]
b[2,3]
b[3][2:]


c
c[2][0][1:4]



array([18, 19, 20])

In [20]:
import numpy as np
# aggregate functions
#1) np.sum(var) --> it will return the sum of all the values present in the array
#2) np.min(var) --> it will return the min value present in the array
#3) np.max(var) --> it will return the max value present in the array
#4)np.mean(var) --> it will return mean or avg value of the array

a=np.arange(1,25)
b=a.reshape((4,6))
c=a.reshape((3,2,4))

np.sum(a)
np.sum(b)
np.sum(c)


np.min(a)
np.min(b)
np.min(c)


np.max(a)
np.max(b)
np.max(c)

print(a.ndim)
print(b.ndim)
print(c.ndim)

np.mean(a)
b.mean()
c.mean()

1
2
3


np.float64(12.5)

In [ ]:
#Filtering conditions
#syntax :- var[condition]


ages=np.array([[17,34,65,23,72,18,45,12,25,11],
               [22,42,16,46,38,12,62,54,16,28]])

#FIND AGE GREATER THAN 60
ages[ages>60]

#find age <18
ages[ages<18]

a=np.arange(1,25)
a
a[a>18]


#logical operators
#AND(&)
#OR (|)
#NOT (~)
 

 #find ages which are >18 and <60

ages=np.array([[17,34,65,23,72,18,45,12,25,11],
               [22,42,16,46,38,12,62,54,16,28]])

ages[(ages>18) & (ages<60)]
(ages>18) & (ages<60) 

array([34, 23, 45, 25, 22, 42, 46, 38, 54, 28])

In [39]:
a=np.arange(1,25)

a[( a % 5 ==0 ) | (a % 7== 0)]

array([ 5,  7, 10, 14, 15, 20, 21])

In [ ]:

ages[~((ages<18) | (ages>60))]

array([34, 23, 18, 45, 25, 22, 42, 46, 38, 54, 28])

In [ ]:
#find age>18 and age<60
ages[(ages<18) | (ages>60)]

# or

ages[~((ages>18) & (ages<60))]



array([17, 65, 72, 18, 12, 11, 16, 12, 62, 16])

In [62]:
#np.where(condition,TRUE,FALSE)
# It is also known as Ternary operations

i = np.identity(4)


np.where(i==1,'tingtingting','lalalala')




array([['tingtingting', 'lalalala', 'lalalala', 'lalalala'],
       ['lalalala', 'tingtingting', 'lalalala', 'lalalala'],
       ['lalalala', 'lalalala', 'tingtingting', 'lalalala'],
       ['lalalala', 'lalalala', 'lalalala', 'tingtingting']], dtype='<U12')

In [70]:
a=np.arange(1,25)
b=a.reshape((4,6))
c=a.reshape((3,2,4))
np.where(b>20,0,b)
c=a.reshape((3,2,4))
np.where(c % 5==0,0,c)


array([[[ 1,  2,  3,  4],
        [ 0,  6,  7,  8]],

       [[ 9,  0, 11, 12],
        [13, 14,  0, 16]],

       [[17, 18, 19,  0],
        [21, 22, 23, 24]]])